# Numpy Optimisation

In [31]:
import numpy as np
np. seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [32]:
x = np.linspace(0.5,1.5,11)

## Standard function form

In [33]:
def form(x):
  if x > 1:
    sq = np.sqrt(x**2-1)
    result = np.arctan(sq)/sq
  if x < 1:
    sq = np.sqrt(1-x**2)
    result = np.arctanh(sq)/sq
  if x == 1:
    result = 1  
  return result
    
form = np.vectorize(form)  

In [34]:
form(x)

array([1.52069199, 1.37326536, 1.25407418, 1.1552453 , 1.07170484,
       1.        , 0.93768155, 0.88295418, 0.83446647, 0.79117842,
       0.75227469])

## Alternative one-liners

In [35]:
alternative1 = lambda x : np.real( 
  np.nan_to_num(np.arctan(np.emath.sqrt(x**2-1))/np.emath.sqrt(x**2-1),nan=1.))

In [36]:
alternative2 = lambda x : np.real(np.arctan(np.emath.sqrt(x**2-1))/np.emath.sqrt(x**2-1))

In [37]:
form(x) - alternative1(x)

array([ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.11022302e-16,  1.11022302e-16,
        0.00000000e+00,  1.11022302e-16,  0.00000000e+00])

In [38]:
form(x) - alternative2(x)

array([ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,             nan,  1.11022302e-16,  1.11022302e-16,
        0.00000000e+00,  1.11022302e-16,  0.00000000e+00])

In [39]:
%%timeit
form(x)

29.5 µs ± 1.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [40]:
%%timeit
alternative1(x)

62.8 µs ± 90.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
%%timeit
alternative2(x)

34.6 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Interpolate!

In [54]:
from scipy.interpolate import interp1d
xx = np.linspace(1e-2,100,1000000)
alternative3 = interp1d(xx,form(xx))

In [55]:
form(x)-alternative3(x)

array([-5.06347786e-09, -3.37922823e-09, -2.17946794e-09, -1.29116140e-09,
       -6.15250295e-10, -9.05677755e-11, -2.75434897e-10, -4.54944526e-10,
       -5.18973198e-10, -5.12753395e-10, -4.64330130e-10])

In [57]:
%%timeit
alternative3(x)

19.5 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
